### ISSUE TITLE
Bad coloring?

### ISSUE THREAD

**Issue by fahad462** [emilwallner/Coloring-greyscale-images#11]
Hey,
I was trying to color the image of women lena which has been used in image processing from the beginning using the full version. All of the result is pretty much bad.
this is the image and ur default images is also there.
![lena](https://user-images.githubusercontent.com/25960803/79238929-cc3b0880-7e91-11ea-8ce9-95bffcbdddac.jpg)

outputs

![img_8](https://user-images.githubusercontent.com/25960803/79239023-e674e680-7e91-11ea-8c25-462a7234d002.png)
![img_0](https://user-images.githubusercontent.com/25960803/79239042-ed035e00-7e91-11ea-8d6b-95061f105bc4.png)

I am not sure what is wrong!
Help me out.

**Comment by animalecs** [comment]
I'm facing the same problem but my images are pink/violet instead of green

**Comment by fahad462** [comment]
@emilwallner help us out man!

**Comment by emilwallner** [comment]
If you are having installation issues, try the ready-made version on FloydHub. If you are on a budget you can upload it to Google Colab, if you do, please ping me the link so you can help other people in your situation.
