### ISSUE TITLE
There is a problem of full_version

### ISSUE THREAD

**Issue by name80bits** [emilwallner/Coloring-greyscale-images#3]
Can you help me to fix this problem? I don't know why it occur.

Error :
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781

Deatil: : 
Using TensorFlow backend.
1.7.0
WARNING:tensorflow:From /root/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Epoch 1/100
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781
	 [[Node: concatenate_1/concat = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2d_211/Relu, reshape_1/Reshape, concatenate_1/concat/axis, conv2d_211/Relu:1, reshape_1/Reshape:1, DMT/_19)]]

**Comment by emilwallner** [comment]
It's an error in your installation. If you want it to work out of the box, try running it on floyhub, details are in the article.
