### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by ChrisFH97** [emilwallner/Coloring-greyscale-images#5]
X = np.array(X, dtype=float)
ValueError: setting an array element with a sequence on Line 15

Any reason why this would happen

**Comment by joshink** [comment]
Better late than never...

You're loading images with different sizes which makes it impossible for numpy to determine the dimensions. I used opencv to resize, but you can use PIL or skimage.

```python
import cv2

X = np.array([cv2.resize(i, (256, 256)) for i in X], dtype=float)
```
