### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Maria97120** [emilwallner/Coloring-greyscale-images#7]
where is the “calc_output_and_feature_size.py”in GAN_version？thank you

**Comment by Maria97120** [comment]
’from models.utils.calc_output_and_feature_size import calc_output_and_feature_size‘don't have this file in GAN version.ModuleNotFoundError: No module named 'models.utils.calc_output_and_feature_size'

**Comment by VincentRagusa** [comment]
also having this problem

**Comment by emilwallner** [comment]
Thanks for reporting - fixed!
